### ISSUE TITLE
Airline not showing correct fonts.

### ISSUE THREAD

**Issue by favetelinguis** [Integralist/ProVim#2]
Are there any additional installs more then moving .vimrc and .vim to home directory to get the proper looking fonts for airline? Also my theme does not look the same as the image in the book.

I see in the .vimrc file that you activate power line fonts but do i also need to install them then or are they included in your repo?

**Comment by Integralist** [comment]
Hi, yes the power line fonts are within this repo:

https://github.com/Integralist/ProVim/tree/master/fonts

If you're on a Mac you can install them using the native FontBook app. 

Have you installed the terminal theme? Double click on the relevant `.terminal` theme to install it (Mac only):

https://github.com/Integralist/ProVim/tree/master/themes

You'll need to then make a change to the terminal theme within the `Terminal.app`'s preferences pane: find the installed theme and change the font to be the powerline font. 

That should be all you need to do.

**Comment by favetelinguis** [comment]
That works, thanks great book!

**Comment by Integralist** [comment]
Great stuff :+1: glad I could help.
