### ISSUE TITLE
The shell is not transparent anymore with the theme

### ISSUE THREAD

**Issue by silentnights** [Integralist/ProVim#5]
Hi,
With this config the shell is not transparent anymore, I wonder if it something that can be fixed, or it depends on the theme choice?

**Comment by Integralist** [comment]
Hi @silentnights i think that may just be the choice of theme I'm using. Between the various OS', terminal emulators (+ their themes), shells and user configuration it can be difficult to find a consistent experience. 

I'd suggest experimenting with different themes

**Comment by silentnights** [comment]
Hi @Integralist Thank you for your answer. I found that adding "hi Normal guibg=NONE ctermbg=NONE" to my .vimrc solves the problem, while still maintains the text colors.

I think the theme is setting the background color, which overrides the transparency of the terminal.
