### ISSUE TITLE
Better Clarification Of .terminal Files

### ISSUE THREAD

**Issue by mcorby17** [Integralist/ProVim#7]
I've been going through your book "ProVim" and ran into something that I believe should be better clarified. 

In "Choosing A New Theme For Your Terminal", it should be specified that you can only open the .terminal files if you're running MacOS. I'm using Ubuntu Linux and could not get the file to open. It was't until I did some research on the internet that I found out about MacOS and .terminal files.

Since you gave options for installing vim on Linux and Windows, I think there should be a section describing how you will not be able to use the .terminal files unless you're running MacOS.

Apart from this the book has been great so far!

**Comment by CMON1975** [comment]
Same scenario, same issue, wondering what the solution is for Linux.

**Comment by Integralist** [comment]
Agreed, this wasn't as clear as it should have been (apologies).

The solution depends on your Linux distribution really.

For example, here are some terminal themes for Gnome you can try...

https://github.com/Anthony25/gnome-terminal-colors-solarized

https://github.com/Mayccoll/Gogh/blob/master/README.md
