### ISSUE TITLE
Unrendered character and unwanted echo of last command after setup

### ISSUE THREAD

**Issue by khipukamayuq** [Integralist/ProVim#9]
![screenshot_2017-12-07_10-44-55](https://user-images.githubusercontent.com/16020142/33771179-14183e5e-dbfe-11e7-928b-62ef175d9d31.png)
Hi,

Purchased your book from a Humble Bundle a while back. Been popping in and out of it in an attempt to ease into vim. Just recently switched from Linux Mint 17.3 where I had you're .vimrc and parts of your .zshrc mixed with my zprezto settings. Truthfully, had no real idea what I was doing there, but it worked. Now I'm in UbuntuStudio 16.04 with Xfce DE. Still using zsh as my default shell and have cloned my fork of ProVim which seems to work just fine when vim is open. Only difference is now I'm using oh-my-zsh. After each command I enter into terminal I get something like `kcd%` preceding any output to terminal. It didn't start doing this until after I'd followed your book's instructions for vim installation and configuration; which doesn't make sense. It should be something in .zshrc, I'd think, only I never actually touched that except to add `export TERM = 'screen-256color'`. Any ideas on where to look? Nothing seemed obvious to me. Thanks in advance.

**Comment by khipukamayuq** [comment]
So... commenting out my export for 256 colors fixes the issue. But then my vim isn't configured as nicely. Now that I'm using oh-my-zsh I did not use any of your book's recommended .zshrc config except for the now commented out export for 256 colors. Any ideas on why this could be? Or how to get my 256 colors back without this ugly echo? Below is screenshot of terminal after commenting out the export for more colors in .zshrc, and vim complaining about the lack of them.
![screenshot_2017-12-08_09-57-14](https://user-images.githubusercontent.com/16020142/33771213-3ff2f410-dbfe-11e7-82c0-01b061f5c3b4.png)

**Comment by khipukamayuq** [comment]
I figured it out. Verbiage is slightly different in my case. `export TERM=xterm-256color` worked without causing the strange echo that `export TERM="screen-256color"` did.

**Comment by Integralist** [comment]
Awesome. Glad you got it sorted (as my spare time of late has been near non-existent). 🙂
